---
version: '3.7'

services:
  drf-angular:
    build:
      context: .
    container_name: drf-angular
    command: >
      bash -c "python manage.py collectstatic --clear --no-input
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8010:8000
    volumes:
      - drf_data:/app/
      - ./media:/app/media/
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512m
        reservations:
          cpus: '0.40'
          memory: 256m
volumes:
  drf_data:
