# Generated by Django 4.1.7 on 2023-03-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=150)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField()),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
